name: ci

on:
  push:
  pull_request:

jobs:
  build:
    name: build
    # if we are running on a pr sourced from a branch on the same repo, skip the pr run to prevent duplicate runs.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        preset: [linux, windows-cross, android-cross]
    uses: ./.github/workflows/build-preset.yml
    with:
      preset: ${{ matrix.preset }}